### ISSUE TITLE
pop up stays on

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [trgkanki/word_autocomplete#15]
# Bug report

## Describe the bug

Quite often when using your addon I end up with the pop up appearing when I am not supposed to be writing text, so it stays on indefinitely until I click on it (and it won't input a thing btw)

## Reproduction step

> Steps to reproduce the behavior:

1. start writing a card
2. input the word "begin" (given you have the word beginning already somewhere in the db)
3. select it
4. cloze it
5. undo
6. the word is now unclozed but still selected, and the pop up is still on, and will stay on and impede reading as long as I don't click on it. If I click on it it disappears and nothing is input.

I have seen this happend in numerous other occasion, but this is easily reproducible.

A fix could be to add a dumb timeout, or a better one : to not make the popup appear if clicking on it would not result in input.

## Anki/OS versions

- OS: *Ubuntu 18.04*
- Anki version * 2.1.35*

**Comment by phu54321** [comment]
> to not make the popup appear if clicking on it would not result in input

There could be a lot of corner cases to this, and I think this would be hard to implement, due to how javascript works. I wouldn't get notified if `clicking on it would not result in input` would happen, and it's actually quite hard to know if it's the case _without actually trying the substitution_. (and *trying the substituion* means your selection or cursor could get lost... which is what happens during the substitution).

So, this is a major change, and I think this will take some time to fix.

A dumb timeout would be easier to do, but even on the current implementation, the autocomplete box will disappear whenever you press a key or click somewhere else, and on the functionality side, I don't see a difference between it and a timer-based method. If this is a functional issue I'll look into this.

**Comment by thiswillbeyourgithub** [comment]
I agree with you, the dumb timeout seems to be the best option.

> the autocomplete box will disappear whenever you press a key or click somewhere else

I disagree. 1. I rarely have a hand on my mouse, I'm a keyboard person so having to click somewhere is actually a pain. 2. Pressing on a key : everything except an arrow key would be a pain it seems.

I will then use the right arrow most of the time but I think a timeout would be nice.

Thanks a lot :)

**Comment by thiswillbeyourgithub** [comment]
edit : sorry for double posting, but after trying it out, the arrow key work unreliably. I was thinking that if it was so obvious I would have tried it by now. 

So to me, I don't think this can be solved any other way than adding the timeout.

**Comment by phu54321** [comment]
ETA 12/06.
